name: Actions
on:
  push:
    branches: [workflow]
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Issue for the pusher
          body: Issue body
          # assignees: 'fausto-sgobba,aiken3000'
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: 'Everybody'
      - run: |
          echo 'Time: ${{ steps.hello.outputs.time }}'
          echo HELLO: $HELLO
